name: Product Build Workflow

on: [push, pull_request]

permissions:
  contents: write

jobs:
  alpine_linux_cli:
    runs-on: ${{ matrix.runner }}
    name: "Build for Alpine Linux CLI"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container: ${{ matrix.docker_image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
            docker_image: arm64v8/alpine:latest
            reh_gulp_task: vscode-reh-linux-arm64
            reh_filename: server-alpine-arm64.tar.gz
          - runner: ubuntu-24.04
            arch: x64
            docker_image: alpine:latest
            reh_gulp_task: vscode-reh-linux-alpine
            reh_filename: server-linux-alpine.tar.gz
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Install Linux Build Dependencies
        run: apk add nodejs npm g++ python3 make git bash curl perl pkgconfig libsecret-dev krb5-dev libx11-dev libxkbfile-dev

      - name: Install Project Dependencies
        working-directory: ./repository
        run: npm install

      - name: Build Flexpilot Executables
        working-directory: ./repository
        env:
          VSCODE_QUALITY: stable
          BUILD_SOURCEVERSION: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
        run: npm run gulp ${{ matrix.reh_gulp_task }}

      - name: Build Flexpilot Executables
        run: tar -czvf ${{ matrix.reh_filename }} ${{ matrix.reh_gulp_task }}/

      - name: Upload RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reh_filename }}
          path: ${{ matrix.reh_filename }}

  # linux_build:
  #   runs-on: ${{ matrix.runner }}
  #   name: "Build for Linux"
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - runner: ubuntu-24.04-arm
  #           arch: arm64
  #           reh_gulp_task: vscode-reh-linux-arm64
  #           reh_filename: server-linux-arm64.tar.gz
  #         - runner: ubuntu-24.04
  #           arch: x64
  #           reh_gulp_task: vscode-reh-linux-x64
  #           reh_filename: server-linux-x64.tar.gz
  #   steps:
  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v4
  #       with:
  #         path: 'repository'

  #     - name: Set fixed version
  #       id: set_version
  #       run: echo "version=1.96.4" >> $GITHUB_OUTPUT

  #     - name: Check if release exists
  #       id: check_release
  #       uses: actions/github-script@v6
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         script: |
  #           try {
  #             const release = await github.rest.repos.getReleaseByTag({
  #               owner: context.repo.owner,
  #               repo: context.repo.repo,
  #               tag: 'v${{ steps.set_version.outputs.version }}'
  #             });

  #             if (release.data) {
  #               await github.rest.repos.deleteRelease({
  #                 owner: context.repo.owner,
  #                 repo: context.repo.repo,
  #                 release_id: release.data.id
  #               });

  #               await github.rest.git.deleteRef({
  #                 owner: context.repo.owner,
  #                 repo: context.repo.repo,
  #                 ref: 'tags/v${{ steps.set_version.outputs.version }}'
  #               });
  #             }
  #             return true;
  #           } catch (e) {
  #             return false;
  #           }

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v${{ steps.set_version.outputs.version }}
  #         release_name: Release v${{ steps.set_version.outputs.version }}
  #         body: |
  #           Automated release created from push to ${{ github.ref_name }} branch.
  #           Commit: ${{ github.sha }}
  #           Created at: ${{ github.event.repository.updated_at }}
  #         draft: false
  #         prerelease: false

  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"

  #     - name: Install Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install Linux Build Dependencies
  #       run: sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 fakeroot rpm

  #     - name: Install Project Dependencies
  #       working-directory: ./repository
  #       run: npm install

  #     - name: Build Flexpilot Executables
  #       working-directory: ./repository
  #       env:
  #         VSCODE_QUALITY: stable
  #         BUILD_SOURCEVERSION: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
  #       run: npm run gulp ${{ matrix.reh_gulp_task }}

  #     - name: Build Flexpilot Executables
  #       run: tar -czvf archive.tar.gz ${{ matrix.reh_gulp_task }}/

  #     - name: Upload Release Assets
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: |
  #           ${{ github.workspace }}/repository/.build/linux/deb/${{ matrix.arch == 'x64' && 'amd64' || 'arm64' }}/deb/linux-${{ matrix.arch }}.deb
  #           ${{ github.workspace }}/repository/.build/linux/rpm/${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}/linux-${{ matrix.arch }}.rpm
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
