name: Product Build Workflow

on: [push, pull_request]

permissions:
  contents: write

env:
  VSCODE_QUALITY: stable
  CXXFLAGS: -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  LDFLAGS: -static-libstdc++ -static-libgcc

jobs:
  alpine_linux_server_build:
    runs-on: ${{ matrix.runner }}
    name: "Build for Alpine Linux Server"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            docker_image: arm64v8/alpine:latest
            reh_gulp_task: vscode-reh-alpine-arm64
            reh_filename: server-alpine-arm64.tar.gz
          - runner: ubuntu-24.04
            docker_image: alpine:latest
            reh_gulp_task: vscode-reh-linux-alpine
            reh_filename: server-linux-alpine.tar.gz
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Extract commit from product.json
        id: get_commit
        run: echo "BUILD_SOURCEVERSION=$(jq -r '.commit' repository/product.json)" >> $GITHUB_ENV

      - name: Install Linux Build Dependencies
        run: |
          docker run --rm -w /workspace/repository \
            -v ${{ github.workspace }}:/workspace \
            -e VSCODE_QUALITY=$VSOCDE_QUALITY \
            -e BUILD_SOURCEVERSION=$BUILD_SOURCEVERSION \
            ${{ matrix.docker_image }} \
            sh -c "
              chown -R root:root /workspace && \
              apk add nodejs npm g++ python3 make git bash curl perl pkgconfig libsecret-dev krb5-dev libx11-dev libxkbfile-dev && \
              n=0; until npm install || ((n++ >= 2)); do echo "Retrying..."; sleep 2; done && \
              npm run gulp ${{ matrix.reh_gulp_task }}
            "

      - name: Set Permissions
        run: sudo chown -R $USER:$USER .

      - name: Build Flexpilot Executables
        run: tar -czvf ${{ matrix.reh_filename }} ${{ matrix.reh_gulp_task }}/

      - name: Upload RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reh_filename }}
          path: ${{ matrix.reh_filename }}

  ubuntu_linux_server_build:
    runs-on: ${{ matrix.runner }}
    name: "Build for Ubuntu Linux Server"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            reh_gulp_task: vscode-reh-linux-arm64
            reh_filename: server-linux-arm64.tar.gz
          - runner: ubuntu-24.04
            reh_gulp_task: vscode-reh-linux-x64
            reh_filename: server-linux-x64.tar.gz
          - runner: ubuntu-24.04
            reh_gulp_task: vscode-reh-linux-armhf
            reh_filename: server-linux-armhf.tar.gz
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Extract commit from product.json
        id: get_commit
        run: echo "BUILD_SOURCEVERSION=$(jq -r '.commit' repository/product.json)" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update Package Cache for Ubuntu
        run: sudo apt-get update

      - name: Install Linux Build Dependencies
        run: sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 fakeroot rpm

      - name: Install Project Dependencies
        working-directory: ./repository
        run: n=0; until npm install || ((n++ >= 2)); do echo "Retrying..."; sleep 2; done

      - name: Build Flexpilot Executables
        working-directory: ./repository
        run: npm run gulp ${{ matrix.reh_gulp_task }}

      - name: Build Flexpilot Executables
        run: tar -czvf ${{ matrix.reh_filename }} ${{ matrix.reh_gulp_task }}/

      - name: Upload RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reh_filename }}
          path: ${{ matrix.reh_filename }}

  darwin_server_build:
    runs-on: ${{ matrix.runner }}
    name: "Build for Darwin Server"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-latest
            reh_gulp_task: vscode-reh-darwin-arm64
            reh_filename: server-darwin-arm64.tar.gz
          - runner: macos-13
            reh_gulp_task: vscode-reh-darwin-x64
            reh_filename: server-darwin.tar.gz
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Extract commit from product.json
        id: get_commit
        run: echo "BUILD_SOURCEVERSION=$(jq -r '.commit' repository/product.json)" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Project Dependencies
        working-directory: ./repository
        run: npm install

      - name: Build Flexpilot Executables
        working-directory: ./repository
        run: npm run gulp ${{ matrix.reh_gulp_task }}

      - name: Build Flexpilot Executables
        run: zip -r ${{ matrix.reh_filename }} ${{ matrix.reh_gulp_task }}

      - name: Upload RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reh_filename }}
          path: ${{ matrix.reh_filename }}

  windows_server_build:
    runs-on: windows-latest
    name: "Build for Windows Server"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - reh_gulp_task: vscode-reh-win32-x64
            reh_filename: server-win32-x64.zip
          - reh_gulp_task: vscode-reh-win32-arm64
            reh_filename: server-win32-arm64.zip
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Extract commit from product.json
        id: get_commit
        shell: bash
        run: echo "BUILD_SOURCEVERSION=$(jq -r '.commit' repository/product.json)" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./repository
        run: npm install

      - name: Build Executables
        working-directory: ./repository
        run: npm run gulp ${{ matrix.reh_gulp_task }}

      - name: Build Flexpilot Executables
        shell: pwsh
        run: Compress-Archive -Path ${{ matrix.reh_gulp_task }} -DestinationPath ${{ matrix.reh_filename }}

      - name: Upload RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reh_filename }}
          path: ${{ matrix.reh_filename }}



